// Official Isha Reference Data — Programs, Prerequisites, Practices, and Personas
// Maintained as authoritative ground truth for Seekers Journey

const OFFICIAL_PROGRAMS = [
  {
    id: 'inner_engineering',
    name: 'Inner Engineering',
    shortName: 'IE',
    description: 'A 7-session experiential technology for inner wellbeing imparting the sacred Shambhavi Mahamudra Kriya.',
    category: 'foundational',
    transmitsPractices: ['Shambhavi Mahamudra'],
    prerequisites: [],
    typicalLocations: ['Bengaluru', 'Delhi', 'Mumbai', 'Coimbatore Ashram', 'IYC Tennessee', 'Online'],
    duration: '7 Days / 4 Days Residential',
    icon: '🏛️',
  },
  {
    id: 'bhava_spandana',
    name: 'Bhava Spandana Program',
    shortName: 'BSP',
    description: 'A profound 4-day residential immersion taking the seeker beyond physical and psychological limitations into unbounded devotion.',
    category: 'advanced',
    prerequisites: ['inner_engineering'],
    typicalLocations: ['Isha Yoga Center, Coimbatore', 'IYC Tennessee'],
    duration: '4 Days Residential',
    icon: '🌸',
  },
  {
    id: 'shoonya_intensive',
    name: 'Shoonya Intensive',
    shortName: 'Shoonya',
    description: 'An advanced 4-day residential program imparting Shakti Chalana Kriya and the conscious stillness of Shoonya meditation.',
    category: 'advanced',
    transmitsPractices: ['Shoonya Meditation', 'Shakti Chalana Kriya'],
    prerequisites: ['inner_engineering'],
    typicalLocations: ['Isha Yoga Center, Coimbatore', 'IYC Tennessee'],
    duration: '4 Days Residential',
    icon: '✨',
  },
  {
    id: 'surya_kriya',
    name: 'Surya Kriya',
    shortName: 'Surya Kriya',
    description: 'A potent 21-step Hatha Yoga practice activating the solar plexus and balancing the system.',
    category: 'hatha_yoga',
    transmitsPractices: ['Surya Kriya'],
    prerequisites: [],
    typicalLocations: ['Local Isha Centers', 'Ashram'],
    duration: '2 Days Weekend Workshop',
    icon: '☀️',
  },
  {
    id: 'yogasanas',
    name: 'Yogasanas',
    shortName: 'Yogasanas',
    description: 'A set of 21 powerful postures to elevate consciousness and stabilize system energy.',
    category: 'hatha_yoga',
    transmitsPractices: ['Yogasanas'],
    prerequisites: [],
    typicalLocations: ['Local Isha Centers', 'Ashram'],
    duration: '2 Days Weekend Workshop',
    icon: '🧘',
  },
  {
    id: 'angamardana',
    name: 'Angamardana',
    shortName: 'Angamardana',
    description: 'A 31-step dynamic fitness system rooted in yoga that strengthens sinews and joints without equipment.',
    category: 'hatha_yoga',
    transmitsPractices: ['Angamardana'],
    prerequisites: [],
    typicalLocations: ['Local Isha Centers', 'Ashram'],
    duration: '2 Days Weekend Workshop',
    icon: '⚡',
  },
  {
    id: 'samyama',
    name: 'Samyama',
    shortName: 'Samyama',
    description: 'An intense 8-day silence program providing the experience of unallocated consciousness and deepest meditative absorption.',
    category: 'advanced',
    transmitsPractices: ['Samyama Sadhana'],
    prerequisites: ['inner_engineering', 'bhava_spandana', 'shoonya_intensive'],
    typicalLocations: ['Isha Yoga Center, Coimbatore', 'IYC Tennessee'],
    duration: '8 Days Residential in Silence',
    icon: '🏔️',
  },
  {
    id: 'sadhanapada',
    name: 'Sadhanapada',
    shortName: 'Sadhanapada',
    description: 'A 7-month residential sadhana and seva immersion offering transformation at the foothills of Velliangiri.',
    category: 'residential',
    prerequisites: ['inner_engineering', 'bhava_spandana', 'shoonya_intensive'],
    typicalLocations: ['Isha Yoga Center, Coimbatore'],
    duration: '7 Months Full-time Ashram Immersion',
    icon: '🙏',
  },
];

const VOLUNTEERING_PATHWAYS = [
  {
    id: 'ashram_seva',
    name: 'Ashram Volunteering (General)',
    description: 'Offering selfless action in the consecrated spaces of the Ashram (Annadanam, Dhyanalinga, Linga Bhairavi).',
    location: 'Isha Yoga Center, Coimbatore',
    icon: '🙏',
  },
  {
    id: 'mahashivratri_seva',
    name: 'Mahashivratri Seva',
    description: 'Serving millions during the night of intense planetary energy and celebration at the Adiyogi.',
    location: 'Foothills of Velliangiri, Coimbatore',
    icon: '🌙',
  },
  {
    id: 'program_volunteering',
    name: 'Program Volunteering',
    description: 'Supporting seekers participating in Inner Engineering, BSP, or Shoonya programs.',
    location: 'City Centers & Ashrams',
    icon: '🤝',
  },
  {
    id: 'community_seva',
    name: 'Local Center / Rally Seva',
    description: 'Active participation in local Isha center activities, tree planting (Cauvery Calling), or monthly satsangs.',
    location: 'Regional Centers',
    icon: '🌱',
  },
];

const SYNTHETIC_PERSONAS = [
  {
    id: 'A',
    name: 'New Seeker',
    tagline: 'Recently initiated, building their initial 40-day Mandala',
    yearsOnPath: 0.3,
    programs: ['inner_engineering'],
    practices: ['Shambhavi Mahamudra'],
    consistency: 0.88,
    activeMandala: true,
    volunteeringCount: 0,
    description: 'Completed Inner Engineering 3 months ago. Dedicated to completing their first 40-day mandala before dawn.',
  },
  {
    id: 'B',
    name: 'Consistent Meditator',
    tagline: '4+ years of unwavering daily dawn practice',
    yearsOnPath: 4.5,
    programs: ['inner_engineering', 'bhava_spandana', 'surya_kriya'],
    practices: ['Shambhavi Mahamudra', 'Surya Kriya', 'Sukha Kriya'],
    consistency: 0.92,
    activeMandala: false,
    volunteeringCount: 3,
    description: 'Practicing Shambhavi and Surya Kriya since 2020 at 5:45 AM with over 1,200 recorded sessions.',
  },
  {
    id: 'C',
    name: 'Inconsistent Returning',
    tagline: 'Restarted practice after a busy career hiatus',
    yearsOnPath: 3.0,
    programs: ['inner_engineering'],
    practices: ['Shambhavi Mahamudra'],
    consistency: 0.54,
    activeMandala: true,
    volunteeringCount: 1,
    description: 'Initiated in 2021, fell off regular sadhana during relocation in 2023, now rebuilding their rhythm.',
  },
  {
    id: 'D',
    name: 'Dedicated Volunteer',
    tagline: 'Balancing daily sadhana with regular Ashram and Mahashivratri Seva',
    yearsOnPath: 5.0,
    programs: ['inner_engineering', 'bhava_spandana', 'angamardana'],
    practices: ['Shambhavi Mahamudra', 'Angamardana'],
    consistency: 0.84,
    activeMandala: false,
    volunteeringCount: 14,
    description: 'Regular volunteer for Mahashivratri, Annadanam, and local weekend Inner Engineering programs.',
  },
  {
    id: 'E',
    name: 'Advanced Seeker',
    tagline: 'Completed Samyama & Sadhanapada with comprehensive Hatha Yoga',
    yearsOnPath: 6.5,
    programs: ['inner_engineering', 'bhava_spandana', 'shoonya_intensive', 'surya_kriya', 'yogasanas', 'samyama'],
    practices: ['Shambhavi Mahamudra', 'Surya Kriya', 'Yogasanas', 'Shoonya Meditation', 'Shakti Chalana Kriya'],
    consistency: 0.95,
    activeMandala: false,
    volunteeringCount: 22,
    description: 'Deepened through BSP, Shoonya, and Samyama silence programs; practices complete morning Hatha sequence.',
  },
  {
    id: 'F',
    name: 'Community Pillar',
    tagline: 'Hosts monthly satsangs and coordinates regional sadhana circles',
    yearsOnPath: 3.5,
    programs: ['inner_engineering', 'surya_kriya'],
    practices: ['Shambhavi Mahamudra', 'Surya Kriya', 'AUM Chanting'],
    consistency: 0.78,
    activeMandala: false,
    volunteeringCount: 8,
    description: 'Active coordinator connecting local practitioners, arranging group meditations, and community outreach.',
  },
  {
    id: 'G',
    name: 'Quiet Consistent Seeker',
    tagline: 'Deep personal contemplative sadhana with high private reflections',
    yearsOnPath: 4.0,
    programs: ['inner_engineering', 'shoonya_intensive'],
    practices: ['Shambhavi Mahamudra', 'Shoonya Meditation'],
    consistency: 0.94,
    activeMandala: false,
    volunteeringCount: 2,
    description: 'Very private practice routine with rich personal journal reflections on breath, stillness, and conscious awareness.',
  },
];

module.exports = {
  OFFICIAL_PROGRAMS,
  VOLUNTEERING_PATHWAYS,
  SYNTHETIC_PERSONAS,
};
